<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign up | DSI-ISET-BIzerte</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-offset-2">
                <div class="page-header">
                    <h2>Employee Registration Form</h2>
                </div>
                <p>Please fill all fields in the form</p>
                <form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="post">
                <div class="form-group ">
                        <label>firstname</label>
                        <input type="text" name="firstname" class="form-control" value="<?= $_POST[''] ?? '' ?>" placeholder="first name must contain only letters" maxlength="50" required="required">
                        <span class="text-danger"><?php if (isset($name_error)) echo $name_error; ?></span>
                    </div>
                    <div class="form-group ">
                        <label>lastname</label>
                        <input type="text" name="lastname" class="form-control" value="<?= $_POST[''] ?? '' ?>" placeholder="last name must contain only letters" maxlength="50" required="required">
                        <span class="text-danger"><?php if (isset($name_error)) echo $name_error; ?></span>
                    </div>
                    <div class="form-group ">
                        <label>sexe</label>
                        <br>    
                        <input type='radio' name='sex' value="<?= $_POST[''] ?? '' ?>"/>Male
                        <input type='radio' name='sex' value="<?= $_POST[''] ?? '' ?>"/>Female
                    </div>
                    <div class="form-group ">
                        <label>Departement</label>
                        <input type="text" name="departement" class="form-control" value="<?= $_POST[''] ?? '' ?>" placeholder="departement name must contain only letters, numbers and space" maxlength="50" required="required">
                        <span class="text-danger"><?php if (isset($departement_error)) echo $departement_error; ?></span>
                    </div>
                    <div class="form-group ">
                        <label>Ville</label>
                        <input type="text" name="ville" class="form-control" value="<?= $_POST[''] ?? '' ?>" placeholder="ville must contain only letters and space" maxlength="50" required="required">
                        <span class="text-danger"><?php if (isset($ville_error)) echo $ville_error; ?></span>
                    </div>
                    <div class="form-group ">
                        <label>Telephone</label>
                        <input type="text" name="telephone" class="form-control" value="<?= $_POST[''] ?? '' ?>" placeholder="can't be less than eight numbers" maxlength="50" required="required">
                        <span class="text-danger"><?php if (isset($telephone_error)) echo $telephone_error; ?></span>
                    </div>
                    <div class="form-group">
                        <label>Username</label>
                        <input type="text" name="username" class="form-control" value="<?= $_POST['username'] ?? '' ?>" maxlength="50" required="required" placeholder="username must contain only letters, numbers and space">
                        <span class="text-danger"><?php if (isset($username_error)) echo $username_error; ?></span>
                    </div>
                    <div class="form-group ">
                        <label>Email</label>
                        <input type="email" name="email" class="form-control" value="<?= $_POST['email'] ?? '' ?>" placeholder="fooooolen@example.com" maxlength="50" required="required">
                        <span class="text-danger"><?php if (isset($email_error)) echo $email_error; ?></span>
                    </div>
                    <div class="form-group">
                        <label>Password</label>
                        <input type="password" name="password" class="form-control" placeholder="can't be less than 6 characters" required="required">
                        <span class="text-danger"><?php if (isset($password_error)) echo $password_error; ?></span>
                    </div>  
                    <div class="form-group">
                        <label>Confirm Password</label>
                        <input type="password" name="cpassword" class="form-control" placeholder="confirm password" required="required">
                        <span class="text-danger"><?php if (isset($cpassword_error)) echo $cpassword_error; ?></span>
                    </div>
                    <div class="form-group">
                        <label>Date de regestiration</label>
                        <input type="date" name="date" class="form-control" value="<?= $_POST[''] ?? '' ?>" required="required">

                    </div>
                    <input type="submit" class="btn btn-block btn-primary" name="signup" value="submit">
                    <div class="text-center">
                        Already have a account?<a href="login.php" class="btn btn-default">Login</a>
                    </div>
                </form>
            </div>
        </div>    
    </div>
</body>
</html>